### ISSUE TITLE
Crash on missing ConfigOption

### ISSUE THREAD

**Issue by bamborough** [ShiftMediaProject/FFVS-Project-Generator#1]
When getCongfigOption() ifails to find an option, the end() iterator may be dereferenced.

e.g. projectGenerator::buildDependencyDirs (line 194) on processing libaacplus.

**Comment by Sibras** [comment]
libaacplus was only removed from ffmpeg a couple of days ago hence why this error hasnt cropped up before. It has however been fixed now in the repo.
