### ISSUE TITLE
support for new fftools folder

### ISSUE THREAD

**Issue by pkviet** [ShiftMediaProject/FFVS-Project-Generator#13]
Hi
a very recent commit has moved all ffmpeg.c, etc, files to fftools directory.
When starting one of the bat files of this project I therefore run into an error because the Makefile for ffmpeg can't be found.
I haven't seen any easy fix. In the bat, I pointed ffmpeg.h to fftools/ffmpeg.h ; but this doesn't seem to carry to the detection of associated makefile .
Thanks

**Comment by Sibras** [comment]
Yep, Thats a very recent commit (i.e. yesterday) so the tool hasnt been updated to support it yet. The new release will come out this weekend which will add proper support.

**Comment by pkviet** [comment]
thanks !
