### ISSUE TITLE
Lots of errors during avcodec project generation

### ISSUE THREAD

**Issue by pkviet** [ShiftMediaProject/FFVS-Project-Generator#18]
Hi,
when starting the generator against FFmpeg master (git head  02ba4b9 )  I have a lot of errors thrown:

`E:\Downloads\visual-studio\FFVS>` .\smp_project_generate_noredist.bat
Located FFmpeg source directory at "./ffmpeg/"

Creating project_get_dependencies.bat...

Do you want to download/update the required dependency projects (Y/N)?n
Running project generator...
Project generator (this may take several minutes, please wait)...
  Passing configure file...
  Outputting config.h...
  Outputting avconfig.h...
  Outputting ffversion.h...
  Outputting enabled components file libavcodec/bsf_list.c...
  Outputting enabled components file libavformat/protocol_list.c...
  Generating from Makefile (./ffmpeg/libavcodec/MakeFile)...
  Generating from Makefile (./ffmpeg/libavcodec/x86/MakeFile)...
  Generating missing DCE symbols (libavcodec)...
  Generating project exports file (libavcodec)...
Invalid switch - "".
  Error: Errors detected during compilation :-
         error C2143: syntax error: missing ':' before ','
         error C2059: syntax error: ','
         error C2059: syntax error: '}'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2371: 'PutBitContext': redefinition; different basic types
         error C2143: syntax error: missing ';' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2371: 'PutBitContext': redefinition; different basic types
         error C2143: syntax error: missing ';' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2371: 'PutBitContext': redefinition; different basic types
         error C2143: syntax error: missing ';' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2371: 'PutBitContext': redefinition; different basic types
         error C2143: syntax error: missing ';' before '*'
         error C2059: syntax error: 'type'
         error C2059: syntax error: ')'
         error C2143: syntax error: missing ')' before '*'
         error C2143: syntax error: missing '{' before '*'
         error C2371: 'PutBitContext': redefinition; different basic types
         error C2143: syntax error: missing ';' before '*'
         error C2059: syntax error: ')'
         error C2054: expected '
         error C2065: 'JLSState': undeclared identifier
         error C2297: '*': illegal, right operand has type 'int *'
         error C2065: 'JLSState': undeclared identifier
         error C2059: syntax error: '='
         error C2223: left of '->bpp' must point to struct/union
         Unknown error detected. See ffvs_log.txt for further details.
`
Here's the ffvs.log
[ffvs_log.txt](https://github.com/ShiftMediaProject/FFVS-Project-Generator/files/1545087/ffvs_log.txt)

First time I'm having this kind of error, so I don't know how to fix it.

**Comment by Sibras** [comment]
This has nothing to do with FFVS tool. The current FFmpeg master branch is broken and wont compile correctly so until it is fixed in upstream FFmpeg there is nothing that I can do. There are fixes that have been submitted to the FFmpeg mailing list but are still pending being applied.

This has been around a little while so any FFmpeg master from the last couple of weeks does not compile with msvc.

**Comment by pkviet** [comment]
Hi
thanks for the clarification ; I had seen those patches but oddly did not make the connexion. 
best

**Comment by pkviet** [comment]
ps: Michael pushed a few hours ago the MSVC patch

**Comment by Sibras** [comment]
Yep, However this only fixes the compilation error. Theres still a runtime error due to atomics that needs to be pushed yet.
