### ISSUE TITLE
Not working with FFmpeg release 4.0

### ISSUE THREAD

**Issue by JiaLinQuan** [ShiftMediaProject/FFVS-Project-Generator#20]
Hi, 
I just pulled your git source and built binary successfully.
But it is not working with ffmpeg release 4.0 now but works with ffmpeg release 3.4.
This is the config options I tried with release 4.0.
--enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib --disable-lzma --disable-sdl2 --toolchain=msvc

I can see that there are some updates in release 4.0 recently so maybe  this project_generate is not working now?

**Comment by Sibras** [comment]
What are the errors that you are getting? I use FFVS to build FFmpeg source weekly and haven't had any issues.
Try adding the log so I can see whats going on.
