### ISSUE TITLE
last release failing on avfilter

### ISSUE THREAD

**Issue by pkviet** [ShiftMediaProject/FFVS-Project-Generator#22]
Hi
you had a commit to address the avfilter api change (https://github.com/FFmpeg/FFmpeg/commit/8f1382f80e0d4184c54c14afdda6482f050fbba7#diff-69f1b53ffbf52f3927df987561b6e9b2); yet I get the following error  with project-generate.exe (with the no-redist script):

> Invalid switch - "".
  Error: Errors detected during compilation :-
         error C2065: 'ff_abench_filter': undeclared identifier
         error C2065: 'ff_acompressor_filter': undeclared identifier
         error C2065: 'ff_acontrast_filter': undeclared identifier
         error C2065: 'ff_acopy_filter': undeclared identifier
         error C2065: 'ff_acue_filter': undeclared identifier
         error C2065: 'ff_acrossfade_filter': undeclared identifier
         error C2065: 'ff_acrusher_filter': undeclared identifier
         error C2065: 'ff_adeclick_filter': undeclared identifier
         error C2065: 'ff_adeclip_filter': undeclared identifier
         error C2065: 'ff_adelay_filter': undeclared identifier
         error C2065: 'ff_aderivative_filter': undeclared identifier
         error C2065: 'ff_aecho_filter': undeclared identifier
         error C2065: 'ff_aemphasis_filter': undeclared identifier
         error C2065: 'ff_aeval_filter': undeclared identifier
         error C2065: 'ff_afade_filter': undeclared identifier
         error C2065: 'ff_afftfilt_filter': undeclared identifier
         error C2065: 'ff_afir_filter': undeclared identifier
         error C2065: 'ff_aformat_filter': undeclared identifier
         error C2065: 'ff_agate_filter': undeclared identifier
         error C2065: 'ff_aiir_filter': undeclared identifier
         error C2065: 'ff_aintegral_filter': undeclared identifier
         error C2065: 'ff_ainterleave_filter': undeclared identifier
         error C2065: 'ff_alimiter_filter': undeclared identifier
         error C2065: 'ff_allpass_filter': undeclared identifier
         error C2065: 'ff_aloop_filter': undeclared identifier
         error C2065: 'ff_amerge_filter': undeclared identifier
         error C2065: 'ff_ametadata_filter': undeclared identifier
         error C2065: 'ff_amix_filter': undeclared identifier
         error C2065: 'ff_anequalizer_filter': undeclared identifier
         error C2065: 'ff_anull_filter': undeclared identifier
         error C2065: 'ff_apad_filter': undeclared identifier
         error C2065: 'ff_aperms_filter': undeclared identifier
         error C2065: 'ff_aphaser_filter': undeclared identifier
         error C2065: 'ff_apulsator_filter': undeclared identifier
         error C2065: 'ff_arealtime_filter': undeclared identifier
         error C2065: 'ff_aresample_filter': undeclared identifier
         error C2065: 'ff_areverse_filter': undeclared identifier
         error C2065: 'ff_aselect_filter': undeclared identifier
         error C2065: 'ff_asendcmd_filter': undeclared identifier
         error C2065: 'ff_asetnsamples_filter': undeclared identifier
         error C2065: 'ff_asetpts_filter': undeclared identifier
         error C2065: 'ff_asetrate_filter': undeclared identifier
         error C2065: 'ff_asettb_filter': undeclared identifier
         error C2065: 'ff_ashowinfo_filter': undeclared identifier
         error C2065: 'ff_asidedata_filter': undeclared identifier
         error C2065: 'ff_asplit_filter': undeclared identifier
         error C2065: 'ff_astats_filter': undeclared identifier
         error C2065: 'ff_astreamselect_filter': undeclared identifier
         error C2065: 'ff_atempo_filter': undeclared identifier
         error C2065: 'ff_atrim_filter': undeclared identifier
         error C2065: 'ff_bandpass_filter': undeclared identifier
         error C2065: 'ff_bandreject_filter': undeclared identifier
         error C2065: 'ff_bass_filter': undeclared identifier
         error C2065: 'ff_biquad_filter': undeclared identifier
         error C2065: 'ff_channelmap_filter': undeclared identifier
         error C2065: 'ff_channelsplit_filter': undeclared identifier
         error C2065: 'ff_chorus_filter': undeclared identifier
         error C2065: 'ff_compand_filter': undeclared identifier
         error C2065: 'ff_compensationdelay_filter': undeclared identifier
         error C2065: 'ff_crossfeed_filter': undeclared identifier
         error C2065: 'ff_crystalizer_filter': undeclared identifier
         error C2065: 'ff_dcshift_filter': undeclared identifier
         error C2065: 'ff_drmeter_filter': undeclared identifier
         error C2065: 'ff_dynaudnorm_filter': undeclared identifier
         error C2065: 'ff_earwax_filter': undeclared identifier
         error C2065: 'ff_ebur128_filter': undeclared identifier
         error C2065: 'ff_equalizer_filter': undeclared identifier
         error C2065: 'ff_extrastereo_filter': undeclared identifier
         error C2065: 'ff_firequalizer_filter': undeclared identifier
         error C2065: 'ff_flanger_filter': undeclared identifier
         error C2065: 'ff_haas_filter': undeclared identifier
         error C2065: 'ff_hdcd_filter': undeclared identifier
         error C2065: 'ff_headphone_filter': undeclared identifier
         error C2065: 'ff_highpass_filter': undeclared identifier
         error C2065: 'ff_highshelf_filter': undeclared identifier
         error C2065: 'ff_join_filter': undeclared identifier
         error C2065: 'ff_loudnorm_filter': undeclared identifier
         error C2065: 'ff_lowpass_filter': undeclared identifier
         error C2065: 'ff_lowshelf_filter': undeclared identifier
         error C2065: 'ff_mcompand_filter': undeclared identifier
         error C2065: 'ff_pan_filter': undeclared identifier
         error C2065: 'ff_replaygain_filter': undeclared identifier
         error C2065: 'ff_sidechaincompress_filter': undeclared identifier
         error C2065: 'ff_sidechaingate_filter': undeclared identifier
         error C2065: 'ff_silencedetect_filter': undeclared identifier
         error C2065: 'ff_silenceremove_filter': undeclared identifier
         error C2065: 'ff_stereotools_filter': undeclared identifier
         error C2065: 'ff_stereowiden_filter': undeclared identifier
         error C2065: 'ff_superequalizer_filter': undeclared identifier
         error C2065: 'ff_surround_filter': undeclared identifier
         error C2065: 'ff_treble_filter': undeclared identifier
         error C2065: 'ff_tremolo_filter': undeclared identifier
         error C2065: 'ff_vibrato_filter': undeclared identifier
         error C2065: 'ff_volume_filter': undeclared identifier
         error C2065: 'ff_volumedetect_filter': undeclared identifier
         error C2065: 'ff_aevalsrc_filter': undeclared identifier
         error C2065: 'ff_anoisesrc_filter': undeclared identifier
         error C2065: 'ff_anullsrc_filter': undeclared identifier
         error C2065: 'ff_hilbert_filter': undeclared identifier
         error C2065: 'ff_sine_filter': undeclared identifier
         error C2065: 'ff_anullsink_filter': undeclared identifier
         error C1003: error count exceeds 100; stopping compilation
         Unknown error detected. See ffvs_log.txt for further details. '

This is with ffmpeg master , last release of ffvs (but i get the same when home compiling ffvs)
ffvs_log.txt repeats the following for each filter:
`./ffmpeg/SMP/libavfilter/filter_list.c(22): error C2065: 'ff_abench_filter': undeclared identifier (compiling source file ffmpeg/libavfilter/allfilters.c)`

**Comment by Sibras** [comment]
Fixed in most recent ffvs master.
