### ISSUE TITLE
nvenc / nvdec supported?

### ISSUE THREAD

**Issue by Ziriax** [ShiftMediaProject/FFVS-Project-Generator#24]
nvenc requires ffnvcodec, but it seems this dependency cannot be specified?

Does your excellent generator support nvenc/nvdec?

**Comment by Ziriax** [comment]
Okay, I found out that I needed to do the following to enable `nvenc`:

- `git clone https://github.com/FFmpeg/nv-codec-headers`
- copy the `include` folder from this cloned repo to the `msvc` folder
- add the option `--enable-ffnvcodec`  to the `PGOPTIONS` environment variable in the batch file.
- run the batch file to generate the project 

Closing this then.

**Comment by Sibras** [comment]
FFVS emulates the behavior specified in the ffmpeg source configure script which currently autodetects nvenc/nvdec so all you need is the headers in the include folder.

Although I have update the bat files so that the explicitly force enable the options anyway.

**Comment by Ziriax** [comment]
Nice! 

I am not sure you need the CUDA SDK, nvenc and nvdec themselves do not need CUDA I believe, but other parts might need it, not sure. It does compile without the CUDA SDK, and nvenc is listed as encoder after the build completes.


I succeeded in making a build, but it is now stuck in an infinite loop in ffmpeg (we are feeding rendered raw images through a Windows pipe). This used to work with an older FFMPEG that we build using the windows build helpers under Ubuntu. So back to drawing board ;-)
