### ISSUE TITLE
DebugDLLStaticDeps

### ISSUE THREAD

**Issue by giachi** [ShiftMediaProject/FFVS-Project-Generator#28]
Hi Sibras

I have a problem with this build and DebugDLLStaticDeps / Template

Thanks for your work !!

Gérard

**Comment by Sibras** [comment]
What exactly is the problem?

**Comment by giachi** [comment]
Hello, 
sorry for my short messages, but it's hard for me to speak English ...

DebugDLLStaticDeps does not exist in: "template_in.vcxproj"
(and of course in the produced files)

Thank you

**Comment by Sibras** [comment]
Support for DebugDLLStaticDeps configuration was deliberately removed when WinRT configurations were added as there was getting to many configs for me to handle (I dont get paid for this)

**Comment by giachi** [comment]
Ok, thanks
