### ISSUE TITLE
VS2013 compiling

### ISSUE THREAD

**Issue by velorom** [ShiftMediaProject/FFVS-Project-Generator#3]
Could not compile in Visual Studio 2013.
in projectGenerator.h:
`ffvs-project-generator\include\projectgenerator.h(252): error C2536: 'ProjectGenerator::ProjectGenerator::asDCETags' : cannot specify explicit initializer for arrays`
This happens because Visual Studio 2013 is not completely C++11. So the solution may be this:

```
    string asDCETags[6];
public:
	ProjectGenerator()
	{
		asDCETags[0] = "ARCH_";
		asDCETags[1] = "HAVE_";
		asDCETags[2] = "CONFIG_";
		asDCETags[3] = "EXTERNAL_";
		asDCETags[4] = "INTERNAL_";
		asDCETags[5] = "INLINE_";
	}
```

Also in projectGenerator.cpp:
uint32_t is declared in stdint.h
So, I added `#include <stdint.h>` there to compile project.

**Comment by Sibras** [comment]
Currently for this project only VS 2015/2017 are tested so using 2013 is not officially supported. That said, I will have a look at fixing any 2013 issues that are reported. In the mean time though you can still use the pre-compiled versions already available on the download page.
If there is something not available in the download versions that requires you to compile it yourself then let me know.

**Comment by Sibras** [comment]
Currently for this project only VS 2015/2017 are tested so using 2013 is not officially supported. That said, I will have a look at fixing any 2013 issues that are reported. In the mean time though you can still use the pre-compiled versions already available on the download page.
If there is something not available in the download versions that requires you to compile it yourself then let me know.
