### ISSUE TITLE
Error: CUDA files detected in project. CUDA compilation is not currently supported

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFVS-Project-Generator#30]
Generating missing DCE symbols (libavdevice)...
Generating project exports file (libavdevice)...
Generating project file (libavdevice)...
Generating from Makefile (../ffmpeg/libavfilter/MakeFile)...
Generating from Makefile (../ffmpeg//libavfilter/dnn/Makefile)...
Generating from Makefile (../ffmpeg/libavfilter/x86/MakeFile)...
Generating missing DCE symbols (libavfilter)...
Generating project exports file (libavfilter)...
Generating project file (libavfilter)...
Error: CUDA files detected in project. CUDA compilation is not currently supported
Generating from Makefile (../ffmpeg/libswscale/MakeFile)...
Generating from Makefile (../ffmpeg/libswscale/x86/MakeFile)...
Generating missing DCE symbols (libswscale)...
Generating project exports file (libswscale)...
Generating project file (libswscale)...

platform: WIN7X64+CUDA10.0

is not support  WIN7X64+CUDA10.0 ?

**Comment by Sibras** [comment]
CUDA is not supported at all. FFmpeg does not use the standard cuda runtime api integration so the existing Visual Studio cuda tools cannot be used without modification. Until suitable tool integration can be created it is not currently possible to compile cuda files using this project.

**Comment by dbyoung720** [comment]
is not support WIN10X64+CUDA10.0 ?

**Comment by Sibras** [comment]
not supported at all, in any form on any OS.
