### ISSUE TITLE
[Feature request] Add clang-cl support

### ISSUE THREAD

**Issue by wangwenx190** [ShiftMediaProject/FFVS-Project-Generator#31]
clang-cl use exactly the same configurations with msvc because it pretends to be msvc on Windows platform by default. So I think it would not be too difficult to add clang-cl support.

PS. May I ask why your repo <https://github.com/ShiftMediaProject/mpv> is not updated for quite a while? It's not on the "Discontinued Projects" list, but it has not been updated for at least one year. It doesn't have a compiled release build as well, however, it's not on the "Non-ReDistributable Projects" list neither.

**Comment by Sibras** [comment]
You should just be able to change the toolset in the output projects properties page if you want to use clang-cl. So I assume you are asking for the generator to automatically change that value for you during generation?

Also mpv was experimental hence why no actual builds were made and I havnt decided yet whether I have the time to support it.

**Comment by wangwenx190** [comment]
> You should just be able to change the toolset in the output projects properties page if you want to use clang-cl.

Yes, you are right. I know I can switch to clang-cl by changing the toolset in VS. It's very simple indeed.

> So I assume you are asking for the generator to automatically change that value for you during generation?

Yes. For example: `--toolchain=clang-cl`. Since clang-cl can share the same configurations with msvc, I guess it would not be difficult to support it.

> Also mpv was experimental hence why no actual builds were made and I havnt decided yet whether I have the time to support it.

OK, I understand now. Thanks for your reply.
