### ISSUE TITLE
Error: Unknown configuration operation found ($target_os)

### ISSUE THREAD

**Issue by RossetaGotStoned** [ShiftMediaProject/FFVS-Project-Generator#37]
Hey guys!
I just got the latest version of ffmpeg and wanted to convert it using your awesome tool but I get following message:

```
Running project generator...
Project generator (this may take several minutes, please wait)...
  Passing configure file...
  Error: Unknown configuration operation found ($target_os)
```

What's the solution?

**Comment by Sibras** [comment]
This was fixed in the source code but a release hadnt been tagged with the necessary fixes. Ive created a new 1.9.3 release which includes the necessary fix.
