### ISSUE TITLE
--disable options doesn't work from 1.9.2 onwards

### ISSUE THREAD

**Issue by richy759** [ShiftMediaProject/FFVS-Project-Generator#38]
There seems to be a regression in disabling components from 1.9.1 onwards.
Expanding on the simple no dependency build, adding --disable-encoders leaves lots of encoders enabled. This is the same for decoders, parsers etc.
`project_generate.exe --enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib --disable-lzma --disable-sdl2 --toolchain=msvc --disable-encoders`
Thanks,
Richard

**Comment by Sibras** [comment]
Should be fixed now. I tested with a variety of different command lines and it appears to be doing the correct thing. If you notice anything then let me know.
