### ISSUE TITLE
How to change code to support to generate vs2022 solution

### ISSUE THREAD

**Issue by wnpllrzodiac** [ShiftMediaProject/FFVS-Project-Generator#39]
I can ONLY get project build aginst vs2010 toolset currently. Need to do a re-target to upgrade to v143 toolset correctly.
Pls give some advice.

**Comment by Sibras** [comment]
The latest version of FFVS (1.10.0) has support for VS2022 generated projects. Make sure your using the latest version and try it out. The default projects in FFmpeg repo have also been updated using the latest FFVS.

**Comment by wnpllrzodiac** [comment]
It's cool. I generated vs2022 solution file successfully. Thank you very much!
