### ISSUE TITLE
error C2373: “ff_h263_chroma_qscale_table”: 重定义

### ISSUE THREAD

**Issue by yunhai2009** [ShiftMediaProject/FFVS-Project-Generator#4]
when i use ffmpeg_generator program to build custom project files,but error C2373: “ff_h263_chroma_qscale_table”: 重定义.

E:\VS-Projects\FFmpeg-3.3.1.r86290\FFVS-Project-Generator\bin>project_generate.e
xe --enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib
 --disable-lzma --disable-sdl --toolchain=msvc --disable-bsf=extract_extradata -
-disable-encoders --disable-muxers
Project generator...
  Passing configure file...
  Warning: Unlisted config dependency found (qsvdec_mpeg2)
  Warning: Unlisted config dependency found (qsvdec_vc1)
  Warning: Unlisted config dependency found (qtkit)
  Warning: Unlisted config dependency found (tls_protocol)
  Outputting config.h...
  Warning: Unknown option in ifa dependency (parisc64) for option (fast_64bit)
  Outputting avconfig.h...
  Outputting ffversion.h...
  Outputting enabled components file libavcodec/bsf_list.c...
  Outputting enabled components file libavformat/protocol_list.c...
  Generating from Makefile (../../ffmpeg/libavcodec/)...
  Warning: Unknown dynamic configuration option (CONFIG_MPEG4_OMX_ENCODER) used
when passing object (omx)
  Generating from Makefile (../../ffmpeg/libavcodec/x86/)...
  Generating missing DCE symbols (libavcodec)...
  Warning: Found unknown macro in DCE condition FMT_H261
  Warning: Found unknown macro in DCE condition FMT_H263
  Warning: Found unknown macro in DCE condition FMT_MJPEG
  Warning: Found unknown macro in DCE condition FMT_MJPEG
  Warning: Found unknown macro in DCE condition FMT_H263
  Warning: Found unknown macro in DCE condition FMT_H263
  Warning: Found unknown macro in DCE condition HUFFMAN_TABLE_OPTIMAL
  Warning: Found unknown macro in DCE condition FMT_MJPEG
  Warning: Found unknown macro in DCE condition CANDIDATE_MB_TYPE_DIRECT
  Warning: Found unknown macro in DCE condition CANDIDATE_MB_TYPE_DIRECT0
  Warning: Found unknown macro in DCE condition MV_DIRECT
  Warning: Found unknown macro in DCE condition FMT_H263
  Warning: Found unknown macro in DCE condition FMT_MPEG1
  Generating project exports file (libavcodec)...
  Error: Errors detected during test compilation :-
    error C2373: “ff_h263_chroma_qscale_table”: 重定义；不同的类型修饰符

    Unknown error detected. See log.txt for further details.
请按任意键继续. . .

**Comment by Sibras** [comment]
In order to try and fix this youll have to post the actual error in English. So if you can post the complete contents of log.txt that should have the required details. Since it appears that this log.txt contains information in your native system language youll have to temporarily change it to English or something in order to get the error into a language i can actually understand.

**Comment by Sibras** [comment]
OK i identified the problem using the command line you gave. It was a rather tricky one but it should be fixed now in the latest 1.5.2 release.
