### ISSUE TITLE
Static compile with libx264

### ISSUE THREAD

**Issue by softworkz** [ShiftMediaProject/FFVS-Project-Generator#46]
This is just a question. I noticed that when compiling with libx264 enabled, I always need to make this change

![image](https://user-images.githubusercontent.com/4985349/168409977-8e35c3c7-075a-4623-8b99-bba1a97d592e.png)

in `libavcodec/libx264.c`

to avoid linker errors. How are you dealing with this on your side?

Thanks,
sw

**Comment by Sibras** [comment]
Yep, thats a known problem. In my local ffmpeg repo those lines have been deleted. I submitted a patch sometime ago but it didnt go anywhere (and then I forgot about it)

[https://ffmpeg.org/pipermail/ffmpeg-devel/2021-October/287426.html](https://ffmpeg.org/pipermail/ffmpeg-devel/2021-October/287426.html)

**Comment by softworkz** [comment]
Thanks, I'll try to promote it a bit. Hadn't seen it at that time..

**Comment by softworkz** [comment]
Checked it out. There has been a patchwork error at the time when you submitted it:

https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAHVN4mh8cZrCCRver6CSkyMzZ6qt6PKb7ZU3m_bhqNgJbwgZAg@mail.gmail.com/

The patch requires rebasing anyway I think.

If you dislike the ffmpeg mailing list (like me), you can submit patches via GitHub pull requests now. Create a PR against the master branch in this repo: https://github.com/ffstaging/FFmpeg and view the automatic bot response.
Finally, you just need to post a comment with `/submit` and your patch will be automatically sent to the mailing list.

**Comment by Sibras** [comment]
Ive seen the github integration which I think is a good idea (and I do wish that it would become the standard) but I have limited time at the moment. The patch I wrote speaks for itself so your welcome to take over it if you have the time

**Comment by softworkz** [comment]
OK fine. I'll try to resubmit it in a while, keeping your signed-off line.

**Comment by softworkz** [comment]
Hi, I just wanted to let you know that I managed to get your patch merged (after some discussion):

https://patchwork.ffmpeg.org/project/ffmpeg/patch/pull.30.v6.ffstaging.FFmpeg.1653568143191.ffmpegagent@gmail.com/

So this is done and working fine, hence I'm closing.

Thanks!
