### ISSUE TITLE
Wrapper Files

### ISSUE THREAD

**Issue by softworkz** [ShiftMediaProject/FFVS-Project-Generator#48]
Hi,

quick question: is there a way to avoid the generation of those `_wrap.c` files?
Why do they exist?

Thanks,
sw

**Comment by Sibras** [comment]
The wrapper files are auto generated whenever there is a source file whos inclusion in the project depends on a config value that is not clearly defined. For instance many config options are disabled when winrt/uwp is being used and as such at the project scope it cant be determined if the file should be included or not (as it depends on whether a winrt or non-winrt project configuration is selected). So the Generator wraps them in a file and surrounds them in the conditional config option. This ways those files are not compiled should the project configuration change and require that functionality.

Most of the time this occurs in winrt but it can also occur in other situation depending on the configuration passed to ffvs.

**Comment by softworkz** [comment]
Thanks for fixing and a big thank you for providing and maintaining this great project!
