### ISSUE TITLE
Could not work for ffmpeg 5.1

### ISSUE THREAD

**Issue by kpld** [ShiftMediaProject/FFVS-Project-Generator#51]
Version 1.11.4 could not work for ffmpeg 5.1, has following compile error:

../ffmpeg-5.1/libavutil/tx.c(350): error C2001: newline in constant
../ffmpeg-5.1/libavutil/tx.c(351): error C2143: syntax error: missing ')' before 'else'

**Comment by kpld** [comment]
ffmpeg 5.1 source code problem, not for this project

**Comment by Sibras** [comment]
Added a commit that should hopefully work around this error
