### ISSUE TITLE
and no avcodec project file?

### ISSUE THREAD

**Issue by aisnote** [ShiftMediaProject/FFVS-Project-Generator#55]
![image](https://user-images.githubusercontent.com/1201634/189001805-eb5df459-a3b2-4a3e-ae81-5635a7a22302.png)

**Comment by Sibras** [comment]
avcodec will be output if you pass the correct options to FFVS. If you do not have avcodec then check your configure options.

**Comment by aisnote** [comment]
with the same config, and compile by msys2 make + vs cl.exe, it do have avcodec

**Comment by aisnote** [comment]
test case like: **--disable-everything --enable-decoder=h264**
As this, should be output avcodec project file, right?

**Comment by aisnote** [comment]
Info: Option (avcodec) was disabled due to an unmet select dependency (null_bsf)
  Info: Option (avformat) was disabled due to an unmet dependency (avcodec)
  Info: Option (linux_perf) was disabled due to an unmet dependency (linux_perf_event_h)
  Info: Option (valgrind_backtrace) was disabled due to an unmet dependency (valgrind_valgrind_h)
  Info: Option (qsv) was disabled due to an unmet dependency (libmfx)
  Info: Option (qsvdec) was disabled due to an unmet select dependency (qsv)
  Info: Option (qsvenc) was disabled due to an unmet select dependency (qsv)
  Info: Option (qsvvpp) was disabled due to an unmet select dependency (qsv)
  Info: Option (rtpdec) was disabled due to an unmet select dependency (asf_demuxer)
  Info: Option (vaapi_encode) was disabled due to an unmet dependency (vaapi)

**Comment by aisnote** [comment]
I add null_bsf, but meet below issue:


Outputting config.h...
  Outputting avconfig.h...
  Outputting ffversion.h...
  Outputting enabled components file libavfilter/filter_list.c...
  Outputting enabled components file libavcodec/codec_list.c...
  Outputting enabled components file libavcodec/parser_list.c...
  Outputting enabled components file libavcodec/bsf_list.c...
  Outputting enabled components file libavformat/demuxer_list.c...
  Outputting enabled components file libavformat/muxer_list.c...
  Outputting enabled components file libavdevice/indev_list.c...
  Outputting enabled components file libavdevice/outdev_list.c...
  Outputting enabled components file libavformat/protocol_list.c...
  Generating from Makefile (./ffmpeg/libswscale/MakeFile)...
  Generating from Makefile (./ffmpeg/libswscale/x86/MakeFile)...
  Generating missing DCE symbols (libswscale)...
  Generating project exports file (libswscale)...
  Generating project file (libswscale)...
  Generating from Makefile (./ffmpeg/libpostproc/MakeFile)...
  Generating missing DCE symbols (libpostproc)...
  Generating project exports file (libpostproc)...
  Generating project file (libpostproc)...
  Generating from Makefile (./ffmpeg/libavformat/MakeFile)...
  Generating missing DCE symbols (libavformat)...
  Generating project exports file (libavformat)...
  Generating project file (libavformat)...
  Generating from Makefile (./ffmpeg/libavcodec/MakeFile)...
  Generating from Makefile (./ffmpeg/libavcodec/x86/MakeFile)...
  Generating missing DCE symbols (libavcodec)...
  Generating project exports file (libavcodec)...

  Generating project exports file (libavcodec)...
Invalid switch - "".
  Error: Errors detected during compilation :-
         error C2099: initializer is not a constant
         error C2099: initializer is not a constant
         error C2099: initializer is not a constant
         error C2099: initializer is not a constant
         error C2099: initializer is not a constant
         error C2099: initializer is not a constant

Any idea?

**Comment by Sibras** [comment]
> test case like: **--disable-everything --enable-decoder=h264** As this, should be output avcodec project file, right?

What version of ffmpeg are you using? As the above command line works as expected with the latest versions of FFVS and FFmpeg

**Comment by aisnote** [comment]
> I add null_bsf, but meet below issue:
> 
> Outputting config.h... Outputting avconfig.h... Outputting ffversion.h... Outputting enabled components file libavfilter/filter_list.c... Outputting enabled components file libavcodec/codec_list.c... Outputting enabled components file libavcodec/parser_list.c... Outputting enabled components file libavcodec/bsf_list.c... Outputting enabled components file libavformat/demuxer_list.c... Outputting enabled components file libavformat/muxer_list.c... Outputting enabled components file libavdevice/indev_list.c... Outputting enabled components file libavdevice/outdev_list.c... Outputting enabled components file libavformat/protocol_list.c... Generating from Makefile (./ffmpeg/libswscale/MakeFile)... Generating from Makefile (./ffmpeg/libswscale/x86/MakeFile)... Generating missing DCE symbols (libswscale)... Generating project exports file (libswscale)... Generating project file (libswscale)... Generating from Makefile (./ffmpeg/libpostproc/MakeFile)... Generating missing DCE symbols (libpostproc)... Generating project exports file (libpostproc)... Generating project file (libpostproc)... Generating from Makefile (./ffmpeg/libavformat/MakeFile)... Generating missing DCE symbols (libavformat)... Generating project exports file (libavformat)... Generating project file (libavformat)... Generating from Makefile (./ffmpeg/libavcodec/MakeFile)... Generating from Makefile (./ffmpeg/libavcodec/x86/MakeFile)... Generating missing DCE symbols (libavcodec)... Generating project exports file (libavcodec)...
> 
> Generating project exports file (libavcodec)... Invalid switch - "". Error: Errors detected during compilation :- error C2099: initializer is not a constant error C2099: initializer is not a constant error C2099: initializer is not a constant error C2099: initializer is not a constant error C2099: initializer is not a constant error C2099: initializer is not a constant
> 
> Any idea?

remove --enable-decoder=mjpeg will fix this.

And FTW, I used FFmpeg4.2.7
