### ISSUE TITLE
vcruntime.h and av_cmp_q 

### ISSUE THREAD

**Issue by DibyaTheXPFan** [ShiftMediaProject/FFVS-Project-Generator#56]
I downloaded latest https://ffmpeg.org/download.html

 Errors detected during compilation :-
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'SDL.h': No such file or directory
         error C1083: Cannot open include file: 'cdio/paranoia/cdda.h': No such file or directory
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_make_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_cmp_q' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C2054: expected '
         error C2085: 'av_q2d' : not in formal parameter list
         error C2143: syntax error : missing ';' before '{'
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
         Based on the above error(s) there are files required for dependency libraries that are not available
         Ensure that any required dependencies are available in 'OutDir' based on the supplied configuration options before trying again.
         Consult the supplied readme for instructions for installing varying dependencies.
         If a dependency has been cloned from a ShiftMediaProject repository then ensure it has been successfully built before trying again.
           Removing the offending configuration option can also be used to remove the error.
Press any key to continue . . .

**Comment by Sibras** [comment]
Your main issue is missing vcruntime.h, this is part of your Visual Studio install which is clearly missing. This indicates that you havnt installed the proper C++ workloads as part of your VS install (Windows Universal CRT).

The other errors are related to not having a valid SDL and cdio-paranoia project available. In order to use these dependencies you need to make sure they are available and built
