### ISSUE TITLE
Cannot find GL & SDL even after putting them , please help 

### ISSUE THREAD

**Issue by DibyaXPP** [ShiftMediaProject/FFVS-Project-Generator#65]
## Command Line
 Just ran smp_project_generate_lgpl3.bat

## Your Environment

* Visual Studio Version: 
* Operating System and Version: Visual Studio 2019 Developer Command Prompt v16.11.18 , on Windows 10 LTSC 2019 

 Error: Errors detected during compilation :-
         error C1083: Cannot open include file: 'SDL.h': No such file or directory
         error C1083: Cannot open include file: 'GL/glext.h': No such file or directory
         Based on the above error(s) there are files required for dependency libraries that are not available
         Ensure that any required dependencies are available in 'OutDir' based on the supplied configuration options before trying again.
         Consult the supplied readme for instructions for installing varying dependencies.
         If a dependency has been cloned from a ShiftMediaProject repository then ensure it has been successfully built before trying again.
           Removing the offending configuration option can also be used to remove the error.

I have created msvc folder , and put include directory with GL as advised 
![direct_structure](https://github.com/ShiftMediaProject/FFVS-Project-Generator/assets/153849991/dd47ca2c-5163-424f-bac9-8a9c3387beda)

**Comment by DibyaXPP** [comment]
I did put FFmpeg inside source folder, unfortunately it said it couldn't find FFMPEG source

**Comment by Sibras** [comment]
Ive added to the scripts in the master branch so that they search for ffmpeg in additional locations. Tjis should fix ffmpeg not being found with your directoty layout.

**Comment by DibyaXPP** [comment]
Thanks a lot ,
