### ISSUE TITLE
Is project_generate.exe the same as ffmpeg_generator.exe ?

### ISSUE THREAD

**Issue by Madsfoto** [ShiftMediaProject/FFVS-Project-Generator#68]
I'm confused why there's two names

**Comment by Sibras** [comment]
Im not sure where you got the second name from, this project only generates `project_generate.exe`

**Comment by Madsfoto** [comment]
The readme: https://github.com/ShiftMediaProject/FFVS-Project-Generator?tab=readme-ov-file#generating-custom-project-files

**Comment by Sibras** [comment]
The readme was incorrect (not sure why it had a different excutable name). Its been fixed now
